-- Create essential tables for Echo Suite Portal

-- Enable the UUID extension to generate UUIDs in Postgres
create extension if not exists "uuid-ossp";

-- A profile row is created for each authenticated user.  Each profile may
-- store additional metadata about the user and is keyed by the Supabase
-- authentication user id (auth.users.id).  Note: Supabase automatically
-- creates the `auth` schema and manages the `auth.users` table for you.
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  notion_db_row_id text,
  n8n_user_id text,
  tone text default 'professional',
  auto_reply_rules jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table profiles enable row level security;

create policy "Allow individual profile access" on profiles
  for all
  using (id = auth.uid());

-- Table for storing inbound emails that have been categorised by the automation
-- workflows.  Each row belongs to a single user via the user_id column.
create table if not exists emails (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  sender text,
  subject text,
  body text,
  category text check (category in ('action','follow_up','noise')),
  received_at timestamptz,
  resolved boolean default false,
  resolved_at timestamptz,
  created_at timestamptz default now()
);

alter table emails enable row level security;
create policy "Allow access to own emails" on emails
  for all
  using (user_id = auth.uid());

-- Meetings for the current day or upcoming events.  The start_time and
-- end_time columns capture the meeting window in UTC.  Attendees may be
-- stored as a comma separated string or JSON depending on your needs.
create table if not exists meetings (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  title text,
  start_time timestamptz,
  end_time timestamptz,
  attendees text,
  created_at timestamptz default now()
);

alter table meetings enable row level security;
create policy "Allow access to own meetings" on meetings
  for all
  using (user_id = auth.uid());

-- Daily summaries generated by the automation.  Each summary belongs to
-- a specific day (`summary_date`) and a part of the day (AM/PM).  Weekly
-- metrics can be stored as JSON in the weekly_metrics column.
create table if not exists summaries (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  summary_date date,
  time_of_day text check (time_of_day in ('AM','PM')),
  content text,
  weekly_metrics jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

alter table summaries enable row level security;
create policy "Allow access to own summaries" on summaries
  for all
  using (user_id = auth.uid());